#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=liquid

mkdir -p ../../../vendor/acer/$DEVICE/proprietary
# bluetooth and wifi
adb pull /system/etc/BCM4325.hcd ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/etc/wifi/nvram.txt ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/etc/wifi/BCM4325.bin ../../../vendor/acer/$DEVICE/proprietary
# sensor
adb pull /system/lib/hw/sensors.salsa.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/hw/lights.qsd8k.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libsensor_yamaha.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libms3c_yamaha.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/bin/sensorcalibutil_yamaha ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/bin/sensorserver_yamaha ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/bin/sensorstatutil_yamaha ../../../vendor/acer/$DEVICE/proprietary
# gps
adb pull /system/lib/libloc.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libloc-rpc.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libcommondefs.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libgps.so ../../../vendor/acer/$DEVICE/proprietary
# egl
adb pull /system/lib/egl/libEGL_adreno200.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv1_CM_adreno200.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv2_adreno200.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/egl/libq3dtools_adreno200.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/libgsl.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/etc/firmware/yamato_pfp.fw ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/etc/firmware/yamato_pm4.fw ../../../vendor/acer/$DEVICE/proprietary
# camera
adb pull /system/lib/libcamera.so ../../../vendor/acer/$DEVICE/proprietary
adb pull /system/lib/liboemcamera.so ../../../vendor/acer/$DEVICE/proprietary



(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/acer/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/acer/__DEVICE__/extract-files.sh

PRODUCT_COPY_FILES := \\
    vendor/acer/__DEVICE__/proprietary/libgps.so:obj/lib/libloc.so \\
    vendor/acer/__DEVICE__/proprietary/libgps.so:obj/lib/libloc-rpc.so \\
    vendor/acer/__DEVICE__/proprietary/libgps.so:obj/lib/libcommondefs.so \\
    vendor/acer/__DEVICE__/proprietary/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \\
    vendor/acer/__DEVICE__/proprietary/BCM4325.hcd:system/etc/firmware/BCM4325.hcd \\
    vendor/acer/__DEVICE__/proprietary/nvram.txt:system/etc/wifi/nvram.txt \\
    vendor/acer/__DEVICE__/proprietary/BCM4325.bin:system/etc/wifi/BCM4325.bin \\
    vendor/acer/__DEVICE__/proprietary/sensors.salsa.so:system/lib/hw/sensors.salsa.so \\
    vendor/acer/__DEVICE__/proprietary/lights.qsd8k.so:system/lib/hw/lights.salsa.so \\
    vendor/acer/__DEVICE__/proprietary/libsensor_yamaha.so:system/lib/libsensor_yamaha.so \\
    vendor/acer/__DEVICE__/proprietary/libms3c_yamaha.so:system/lib/libms3c_yamaha.so \\
    vendor/acer/__DEVICE__/proprietary/sensorcalibutil_yamaha:system/bin/sensorcalibutil_yamaha \\
    vendor/acer/__DEVICE__/proprietary/sensorserver_yamaha:system/bin/sensorserver_yamaha \\
    vendor/acer/__DEVICE__/proprietary/sensorstatutil_yamaha:system/bin/sensorstatutil_yamaha \\
    vendor/acer/__DEVICE__/proprietary/libloc.so:system/lib/libloc.so \\
    vendor/acer/__DEVICE__/proprietary/libloc-rpc.so:system/lib/libloc-rpc.so \\
    vendor/acer/__DEVICE__/proprietary/libcommondefs.so:system/lib/libcommondefs.so \\
    vendor/acer/__DEVICE__/proprietary/libgps.so:system/lib/libgps.so \\
    vendor/acer/__DEVICE__/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \\
    vendor/acer/__DEVICE__/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \\
    vendor/acer/__DEVICE__/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \\
    vendor/acer/__DEVICE__/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \\
    vendor/acer/__DEVICE__/proprietary/libgsl.so:system/lib/libgsl.so \\
    vendor/acer/__DEVICE__/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \\
    vendor/acer/__DEVICE__/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \\
    vendor/acer/__DEVICE__/proprietary/libcamera.so:system/lib/libcamera.so \\
    vendor/acer/__DEVICE__/proprietary/liboemcamera.so:system/lib/liboemcamera.so \\

EOF

./setup-makefiles.sh
